name: Build Push and Deploy to ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECS_CLUSTER: assignment-cluster

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout source
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Login to ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      ##########################################################
      # BUILD AND PUSH API IMAGE
      ##########################################################

      - name: Build API Docker Image
        run: |
          docker build \
            -t assignment-api \
            ./backend/AssignmentApi

      - name: Tag API Docker Image
        run: |
          docker tag assignment-api:latest \
          ${{ steps.login-ecr.outputs.registry }}/assignment-api:latest

      - name: Push API Docker Image
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/assignment-api:latest

      ##########################################################
      # BUILD AND PUSH UI IMAGE
      ##########################################################

      - name: Build UI Docker Image
        run: |
          docker build \
            -t assignment-ui \
            ./frontend

      - name: Tag UI Docker Image
        run: |
          docker tag assignment-ui:latest \
          ${{ steps.login-ecr.outputs.registry }}/assignment-ui:latest

      - name: Push UI Docker Image
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/assignment-ui:latest

      ##########################################################
      # DEPLOY API SERVICE
      ##########################################################

      - name: Force API Deployment
        run: |
          aws ecs update-service \
            --cluster assignment-cluster \
            --service assignment-api \
            --force-new-deployment \
            --region ap-south-1

      ##########################################################
      # DEPLOY UI SERVICE
      ##########################################################

      - name: Force UI Deployment
        run: |
          aws ecs update-service \
            --cluster assignment-cluster \
            --service assignment-ui \
            --force-new-deployment \
            --region ap-south-1