name: Build Push and Deploy ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECS_CLUSTER: assignment-cluster

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Structure
        run: |
          pwd
          find . -name Dockerfile

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      #################################################
      # API IMAGE
      #################################################

      - name: Build API Docker Image
        run: |
          docker build \
            -f ./backend/AssignmentApi/Dockerfile \
            -t assignment-api \
            ./backend/AssignmentApi

      - name: Tag API Image
        run: |
          docker tag assignment-api:latest \
          ${{ steps.login-ecr.outputs.registry }}/assignment-api:latest

      - name: Push API Image
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/assignment-api:latest

      #################################################
      # UI IMAGE
      #################################################

      - name: Build UI Docker Image
        run: |
          docker build \
            -f ./frontend/assignment-ui/Dockerfile \
            -t assignment-ui \
            ./frontend/assignment-ui

      - name: Tag UI Image
        run: |
          docker tag assignment-ui:latest \
          ${{ steps.login-ecr.outputs.registry }}/assignment-ui:latest

      - name: Push UI Image
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/assignment-ui:latest

      #################################################
      # ECS DEPLOYMENT
      #################################################

      - name: Deploy API Service
        run: |
          aws ecs update-service \
            --cluster assignment-cluster \
            --service assignment-api \
            --force-new-deployment \
            --region ap-south-1

      - name: Deploy UI Service
        run: |
          aws ecs update-service \
            --cluster assignment-cluster \
            --service assignment-ui \
            --force-new-deployment \
            --region ap-south-1